stages:
  - static_tests
  - static_analysis
  - build
  - package
  - release
  - deploy

include:
  - project: 'polyflix-do/ci-templates'
    file: '/templates/nodejs.yml'
    ref: main
  - project: 'polyflix-do/ci-templates'
    file: '/jobs/nestjs/package.migrations.yml'
    ref: main
  - project: 'polyflix-do/ci-templates'
    file: '/jobs/nestjs/package.yml'
    ref: main
  - project: 'polyflix-do/ci-templates'
    file: '/jobs/nestjs/test.units.yml'
    ref: main

deploy:kube:
  extends: .kube-deploy
  variables:
    HELM_OPTIONS: "--set image.tag=$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    HELM_RELEASE_NAME: "video"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENVIRONMENT: qa
    - if: $CI_COMMIT_TAG
      variables:
        ENVIRONMENT: production
        ENVIRONMENT_NS: default
        HELM_OPTIONS: "--set image.tag=$CI_COMMIT_TAG"
