FROM ghcr.io/polyflix/dependencies/psql-migration:main

COPY ./dist/resources/migrations migrations
RUN tsc --skipLibCheck true --skipDefaultLibCheck true  ./migrations/*.ts  --outDir "./migrations" || echo "expected error"

