FROM gitlab.polytech.umontpellier.fr:5050/polyflix-do/docker-images/psql-migration:latest

RUN tsc --skipLibCheck true --skipDefaultLibCheck true  ./dist/resources/migrations/*.ts  --outDir "dist/resources/migrations" || echo "expected error"
COPY ./dist/resources/migrations migrations
